apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent-service-blue
  labels:
    app: agent-service
    version: blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: agent-service
      version: blue
  template:
    metadata:
      labels:
        app: agent-service
        version: blue
    spec:
      containers:
      - name: agent-service
        image: sithirandy/agent-service:latest
        ports:
        - containerPort: 5000