apiVersion: apps/v1
kind: Deployment
metadata:
  name: aggregator-service-blue
  labels:
    app: aggregator-service
    version: blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aggregator-service
      version: blue
  template:
    metadata:
      labels:
        app: aggregator-service
        version: blue
    spec:
      containers:
      - name: aggregator-service
        image: sithirandy/aggregator-service:latest
        ports:
        - containerPort: 5003