apiVersion: batch/v1
kind: CronJob
metadata:
  name: aggregator-service
spec:
  schedule: "*/30 * * * *"  # Every 30 minutes
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: aggregator
            image: 715841324407.dkr.ecr.ap-south-1.amazonaws.com/aggregator-service:latest
            args:
            - "python"
            - "app.py"
          restartPolicy: OnFailure