apiVersion: apps/v1
kind: Deployment
metadata:
  name: integration-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: integration-service
  template:
    metadata:
      labels:
        app: integration-service
    spec:
      containers:
      - name: integration-service
        image: 715841324407.dkr.ecr.ap-south-1.amazonaws.com/integration-service:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: integration-service
spec:
  type: ClusterIP
  selector:
    app: integration-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000