apiVersion: v1
kind: Service
metadata:
  name: integration-service-blue
spec:
  selector:
    app: integration-service
    version: blue
  ports:
    - protocol: TCP
      port: 5003
      targetPort: 5003
  type: ClusterIP
