apiVersion: v1
kind: Service
metadata:
  name: notification-service-blue
spec:
  type: LoadBalancer
  selector:
    app: notification-service
    version: blue
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
