apiVersion: v1
kind: Service
metadata:
  name: agent-service-green
spec:
  type: LoadBalancer
  selector:
    app: agent-service
    version: green
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
