apiVersion: v1
kind: Service
metadata:
  name: integration-service-green
spec:
  type: LoadBalancer
  selector:
    app: integration-service
    version: green
  ports:
    - protocol: TCP
      port: 5003
      targetPort: 5003
