apiVersion: v1
kind: Service
metadata:
  name: aggregator-service
spec:
  type: LoadBalancer
  selector:
    app: aggregator-service
    version: green
  ports:
    - protocol: TCP
      port: 5003
      targetPort: 5003

