apiVersion: v1
kind: Service
metadata:
  name: notification-service-green
spec:
  type: LoadBalancer
  selector:
    app: notification-service
    version: green
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 5002
