apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent-service-green
  labels:
    app: agent-service
    version: green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: agent-service
      version: green
  template:
    metadata:
      labels:
        app: agent-service
        version: green
    spec:
      containers:
      - name: agent-service
        image: 715841324407.dkr.ecr.ap-south-1.amazonaws.com/agent-service
        ports:
        - containerPort: 5000