apiVersion: apps/v1
kind: Deployment
metadata:
  name: aggregator-service-green
  labels:
    app: aggregator-service
    version: green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aggregator-service
      version: green
  template:
    metadata:
      labels:
        app: aggregator-service
        version: green
    spec:
      containers:
      - name: aggregator-service
        image: 715841324407.dkr.ecr.ap-south-1.amazonaws.com/aggregator-service
        ports:
        - containerPort: 5003
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: DB_PORT
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: DB_NAME
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: DB_PASSWORD
