apiVersion: apps/v1
kind: Deployment
metadata:
  name: integration-service-green
  labels:
    app: integration-service
    version: green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: integration-service
      version: green
  template:
    metadata:
      labels:
        app: integration-service
        version: green
    spec:
      containers:
      - name: integration-service
        image: 715841324407.dkr.ecr.ap-south-1.amazonaws.com/integration-service
        ports:
        - containerPort: 5002
