apiVersion: apps/v1
kind: Deployment
metadata:
  name: integration-service-green
  labels:
    app: integration-service
    version: green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: integration-service
      version: green
  template:
    metadata:
      labels:
        app: integration-service
        version: green
    spec:
      containers:
      - name: integration-service
        image: sithirandy/integration-service:latest
        ports:
        - containerPort: 5002
