apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service-green
  labels:
    app: notification-service
    version: green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notification-service
      version: green
  template:
    metadata:
      labels:
        app: notification-service
        version: green
    spec:
      containers:
      - name: notification-service
        image: sithirandy/notification-service:latest
        ports:
        - containerPort: 5001
