apiVersion: v1
kind: Service
metadata:
  name: agent-service
spec:
  type: LoadBalancer
  selector:
    app: agent-service
    version: blue  # Will be replaced by CI/CD during traffic switch
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
