apiVersion: v1
kind: Service
metadata:
  name: integration-service
spec:
  type: LoadBalancer
  selector:
    app: integration-service
    version: blue  # Will be replaced by CI/CD during traffic switch
  ports:
    - protocol: TCP
      port: 5003
      targetPort: 5003

