apiVersion: v1
kind: Service
metadata:
  name: aggregator-service
spec:
  selector:
    app: aggregator-service
    version: blue
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5003
  type: ClusterIP