apiVersion: v1
kind: Service
metadata:
  name: integration-service
spec:
  selector:
    app: integration-service
    version: blue
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5002
  type: ClusterIP