name: Deploy to Kubernetes (Blue-Green)

on:
  push:
    branches:
      - master

env:
  EKS_CLUSTER_NAME: moon-agent-tracker-cluster
  AWS_REGION: ap-south-1
  DOCKER_IMAGE_AGENT: sithirandy/agent-service
  DOCKER_IMAGE_INTEGRATION: sithirandy/integration-service
  DOCKER_IMAGE_NOTIFICATION: sithirandy/notification-service
  DOCKER_IMAGE_AGGREGATOR: sithirandy/aggregator-service

jobs:
  deploy:
    name: CI/CD for Moon Agent Tracker
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3

    - name: Set up kubeconfig
      run: |
        aws eks update-kubeconfig --name $EKS_CLUSTER_NAME --region $AWS_REGION

    - name: Deploy Blue Environment
      run: |
        kubectl apply -f k8s/blue-green/blue/
        kubectl apply -f k8s/blue-green/services/

    - name: Wait for blue to stabilize
      run: sleep 20

    - name: Run Tests (Post-Deployment)
      run: |
        curl --fail http://$(kubectl get svc agent-service -o jsonpath='{.spec.clusterIP}'):5000 || exit 1

    - name: Switch traffic to Blue
      run: |
        sed -i 's/version: green/version: blue/' k8s/blue-green/services/*.yaml
        kubectl apply -f k8s/blue-green/services/

    - name: Delete Green Deployment (optional cleanup)
      run: |
        kubectl delete -f k8s/blue-green/green/ || true
